export const INCREASE = 'INCREASE';
export const DECREASE = 'DECREASE';

export const COUNTER_REQUEST = 'COUNTER_REQUEST';
export const COUNTER_SUCCESS = 'COUNTER_SUCCESS';
export const COUNTER_FAIL = 'COUNTER_FAIL';

